version: "3"

services:
  django:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_URL=postgres://test:secret@db:5432/testdb
    volumes:
      - .:/app
    command: python app/manage.py runserver 0.0.0.0:8000
  db:
    image: "postgres:12.3"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=testdb
