version: "3"

volumes:
  db_data:
    
services:
  django: &django
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis-db
    links:
      - db
    environment:
      - DATABASE_URL=postgres://test:secret@db:5432/testdb
      - REDIS_URL=redis://redis-db:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.local
    env_file:
      - .env.local
    volumes:
      - .:/app
    command: python app/manage.py runserver 0.0.0.0:8000
  db:
    image: "postgres:12.3"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=testdb
    volumes:
      - db_data:/var/lib/postgresql/data
  redis-db:
    image: redis:6.0.6
  celery-worker:
    <<: *django
    depends_on:
      - db
      - redis-db
    ports: []
    command: celery -A config.celery_app worker --workdir app -l INFO
  celery-beat:
    <<: *django
    depends_on:
      - db
      - redis-db
    ports: []
    command: celery -A config.celery_app beat --workdir app -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
