# Generated by Django 3.0.8 on 2020-08-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('hash', models.CharField(max_length=24, unique=True)),
                ('valid_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.BigIntegerField(default=0)),
            ],
        ),
    ]
