# Generated by Django 3.0.8 on 2020-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
