# Generated by Django 3.1.1 on 2020-09-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='password',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='link',
            name='hash',
            field=models.CharField(max_length=24, unique=True, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=1024, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='link',
            name='valid_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid date'),
        ),
    ]
